name: Presubmit

on:
  pull_request:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup `uv`
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

      - name: Install `prek`
        run: uv tool install prek

      - name: Install Rust nightly toolchain
        uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
        with:
          toolchain: nightly

      - name: Install `cargo-nextest`
        uses: taiki-e/install-action@787505cde8a44ea468a00478fe52baf23b15bccd # v2.75.21
        with:
          tool: nextest

      - name: Restore Rust cache
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1

      - name: Default validation hooks
        run: uv tool run prek run --all-files

      - name: Strict lint
        run: uv tool run prek run clippy --all-files --hook-stage manual

      - name: Full test suite
        run: uv tool run prek run test-workspace --all-files --hook-stage manual
