name: Release Checks

on:
  workflow_call:

permissions:
  contents: read

jobs:
  validate:
    uses: ./.github/workflows/rust-validation.yml
    with:
      llvm-tools-preview: true
      workspace-tests: true
